name: viami
description: Viami project
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # curved navigation bar
  curved_navigation_bar : ^1.0.1


  # animated drawer
  flutter_zoom_drawer: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/

# Custom splash screen
flutter_native_splash:
  image: assets/logo.png
  color: "#0081CF"
  ios: true
  android: true